### ISSUE TITLE
Decoding .tar.bz2 files in a stream?

### ISSUE THREAD

**Issue by Bartvds** [cscott/seek-bzip#1]
I'm looking for a bz2 implementation that is usable as decompressor in a pipe() with `node-tar` to extract .tar.bz2 files. 

Something like:

```
fs.createReadStream(sourceFile)
    .pipe(new Bunzip())
    .pipe(tar.Extract({ path: "folder/path"}))
    .on('close', function () {
    ...
```

Is `seek-bzip` (or any of your other packages) suitable for this?

**Comment by Skywalker13** [comment]
@Bartvds https://github.com/regular/unbzip2-stream
